# Generated by Django 4.1.5 on 2023-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
    ]
