# Generated by Django 4.1.5 on 2023-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_doctor',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
    ]
