# Generated by Django 4.1.5 on 2023-08-27 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_date', models.DateField(null=True)),
                ('Appointment_time', models.TimeField(null=True)),
                ('notes', models.CharField(default='empty', max_length=255)),
                ('payment', models.IntegerField(default=0)),
                ('Appointment_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointmentstatuse')),
                ('doctor', models.ForeignKey(limit_choices_to={'role__role_name': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role__role_name': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
