# Generated by Django 4.1.5 on 2023-08-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('treatment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.treatments')),
            ],
        ),
    ]
