# Generated by Django 4.1.5 on 2023-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_treatment_appointment_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.CharField(blank=True, default='empty', max_length=255, null=True),
        ),
    ]
