# Generated by Django 4.1.5 on 2023-08-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_appointment_id_appointmenttreatment_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
