# Generated by Django 4.1.5 on 2023-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
